name: Deploy to Aptible

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v4
        with:
          type: git
          app: test-deploy
          environment: gurutest
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
